---
- name: Add repository PostgesSQL key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
- name: Add PostgresSQL repository
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"

- name: Install PostgresSQL
  apt:
    name:
      - "postgresql-{{ postgres_version }}"
      - "postgresql-client-{{ postgres_version }}"
    update_cache: yes
  ignore_errors: "{{ ansible_check_mode }}"

- name: Copy PostgresSql configuration file
    template:
      src: postgresql.conf.j2
      dest: /etc/postgresql/postgresql.conf
      owner: postgres
      mode: 0644