version: "3.9"  # optional since v1.27.0
services:
  app:
    build: .
  web:
    image: nginx
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf
