version: "3.9"  # optional since v1.27.0
services:
  app:
    build: .
    ports:
      - "8000:8080"
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker-compose/nginx-conf/nginx.conf:/etc/nginx.conf
