---
- name: nginx systemd
  systemd:
    name: nginx
    enabled: yes
    state: started

- name: restart nginx
  systemd:
      daemon_reload: true
      name: nginx
      state: restarted
  register: restart_nginx_result
  ignore_errors: true


